name: Deploy Firebase Services

on:
  push:
    branches:
      - main
    paths:
      - 'functions/**'
      - 'firestore.rules'
      - 'firestore.indexes.json'
      - 'storage.rules'

jobs:
  deploy-firebase-services:
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Install Firebase CLI
        run: npm install -g firebase-tools@13

      - name: Deploy Firestore Rules
        run: firebase deploy --only firestore:rules --project skinscore-afw5a
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_DEPLOY_TOKEN }}

      - name: Deploy Firestore Indexes
        run: firebase deploy --only firestore:indexes --project skinscore-afw5a
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_DEPLOY_TOKEN }}

      - name: Deploy Storage Rules
        run: firebase deploy --only storage --project skinscore-afw5a
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_DEPLOY_TOKEN }}

      - name: Deploy Cloud Functions
        run: firebase deploy --only functions --project skinscore-afw5a
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_DEPLOY_TOKEN }}