// Export only types and lazy loader, not the actual tools
export type { Tool } from './types';
export { loadTool, preloadTool, getAllToolIds } from './lazy-loader';
export { toolCategories } from './categories';
export {
  toolMetadata,
  getToolMetadata,
  getGroupedToolMetadata,
  getPopularToolsMetadata,
  popularToolIds,
  type ToolMetadata,
} from './tool-metadata';
export { toLazyLoaderId, fromLazyLoaderId } from './tool-id-mapper';

// For backward compatibility during migration
export { toolMetadata as toolData } from './tool-metadata';

// List of all available tool IDs for reference
export const AVAILABLE_TOOLS = [
  'aas',
  'abcdeMelanoma',
  'absis',
  'acneQol',
  'alt70',
  'behcetCriteria',
  'bilagSkin',
  'bpdai',
  'bradenScale',
  'bvasSkin',
  'bwat',
  'casparCriteria',
  'cdasi',
  'cdlqi',
  'ceaRosacea',
  'clasi',
  'ctcaeSkin',
  'dapsa',
  'dasi',
  'dlqi',
  'dssi',
  'easi',
  'essdaiCutaneous',
  'fitzpatrickSkinType',
  'fiveDItch',
  'gags',
  'hecsi',
  'hiscr',
  'hsPga',
  'hurleyStagingHs',
  'igaAcne',
  'igaRosacea',
  'ihs4',
  'iimSontheimer2002',
  'issVis',
  'loscat',
  'masiMmasi',
  'melasqol',
  'mfgScore',
  'mrss',
  'msi',
  'mssHs',
  'mswat',
  'nappaClin',
  'napsi',
  'nrsPruritus',
  'parklandFormula',
  'pasi',
  'pdai',
  'pedisClassification',
  'pest',
  'pgDelphi',
  'pgParacelsus',
  'pgSu',
  'pgaPsoriasis',
  'poem',
  'pssi',
  'push',
  'salt',
  'sasi',
  'sassad',
  'scorad',
  'scorten',
  'scqoli10',
  'sevenPointChecklist',
  'sinbadScore',
  'skindex29',
  'sledaiSkin',
  'sliccCriteria',
  'uas7',
  'uct',
  'utWoundClassification',
  'vasi',
  'vasPruritus',
  'vida',
  'vigaAd',
  'vitiqol',
] as const;

export type ToolId = (typeof AVAILABLE_TOOLS)[number];
